version: "3.9"
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-zwierzegle}
      POSTGRES_PASSWORD: ${DB_USER:-zwierzegle}
      POSTGRES_DB: ${DB_USER:-zwierzegle}

  zwierzegle:
    image: "zwierzegle:latest"
    links:
      - db
    ports: 
      - "127.0.0.1:${PORT:-8080}:8080"
    environment:
      DB_HOST: db
      