springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:true}
  info:
    title: "Zwierzegle API"
    description: "Zwierzegle API - część backend dla projektu Zwierzegle na Projekty Zespołowe 2022"

jwt_secret: PK_TO_MOJA_PASJA_ZWIERZEGLE_2022/2023

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:zwierzegle}"
    username: ${DB_USER:zwierzegle_user}
    password: ${DB_PASS:zwierzegle}
  security:
    user:
      name: config
      password: configPassword