name: Auto Test

on:
  push:
    branches: 
      - '**'

jobs:
  tests:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build and test with Maven
      run: mvn -f backend/pom.xml -B test